# MAVROS Custom Configuration
# Configuration file for custom MAVLink integration

# Robot namespace configuration
robot_name: "tota1"  # Change this to your robot's name (will be used as ROS2 namespace)

# Network configuration
mavlink:
  input_port: 14551   # Port to receive MAVLink messages
  output_port: 14555  # Port to forward messages to MAVROS
  host: "127.0.0.1"   # Host IP address

# MAVROS configuration
mavros:
  fcu_protocol: "v2.0"  # MAVLink protocol version
  
# Custom message configuration
custom_messages:
  tof_ranges_id: 42001
  tof_meta_id: 42002
  wheel_encoders_id: 42003
  
# Optional parameters
wheel_params:
  wheel_separation: 0.3  # meters - distance between wheels for differential drive