# MAVROS Custom Configuration
# Configuration file for custom MAVLink integration

# Robot namespace configuration
robot_name: "tota1"  # Change this to your robot's name (will be used as ROS2 namespace)

# Network configuration
mavlink:
  input_port: 14551   # Port to receive MAVLink messages
  output_port: 14555  # Port to forward messages to MAVROS
  host: "127.0.0.1"   # Host IP address
  gcs_url: ""  # GCS connection URL (optional)
  target_system_id: 20     # MAVLink target system ID
  target_component_id: 200  # MAVLink target component ID
  fcu_protocol: "v2.0"      # MAVLink protocol version

# MAVROS configuration
mavros:
  plugin_config: "mavros_plugins.yaml"  # Path to plugin configuration file
  log_output: "screen"  # Log output destination (screen or log)
  
# Custom message configuration
custom_messages:
  tof_ranges_id: 42001
  tof_meta_id: 42002
  wheel_encoders_id: 42003
  
# Optional parameters
wheel_params:
  wheel_separation: 0.3  # meters - distance between wheels for differential drive