/**:
  ros__parameters:

    # Connection configuration
    fcu_url: udp://127.0.0.1:14551@:14555
    tgt_system: 20
    tgt_component: 200
    fcu_protocol: v2.0

    # Plugin configuration - TOTA custom plugins + essential standard plugins
    plugin_allowlist:
      # TOTA Custom Plugins
      - tof_ranges         # TOF_L7CX_RANGES (42001)
      - tof_meta          # TOF_L7CX_META (42002)
      - wheel_encoders    # WHEEL_ENCODERS (42003)
      - velocity_control  # Velocity command sender
      - vtx_control       # VTX control

      # Essential Standard Plugins
      - imu               # IMU data processing

# Plugin parameters
tof_ranges:
  ros__parameters:
    raw_topic: "~/raw"
    fov_horizontal: 60.0    # Total horizontal field of view in degrees
    fov_vertical: 60.0      # Total vertical field of view in degrees
    resolution: 8           # Grid resolution: 4 for 4x4, 8 for 8x8
    orientation: "z_forward"  # Coordinate frame: "x_forward" or "z_forward"

wheel_encoders:
  ros__parameters:
    joint_states_topic: "~/joint_states"
    ticks_per_revolution: 2048.0  # Testing with different value
