# MAVROS Plugin Configuration
# This file controls which MAVROS plugins are loaded at startup
# Comment out or set to empty list to load all available plugins

plugin_allowlist:
  # Core system plugins  
  # - sys_status       # System status monitoring
  
  # IMU and attitude data
  - imu              # IMU plugin for ATTITUDE/ATTITUDE_QUATERNION messages
  
  # Custom sensor plugins
  - tof_ranges       # TOF L7CX range sensor data (ID: 42001)
  # - tof_meta         # TOF L7CX metadata (ID: 42002)
  - wheel_encoders   # Wheel encoder data (ID: 42003)
  
  # Control plugins
  - velocity_control # Velocity command interface

# Uncomment below to load ALL plugins (ignores allowlist)
# load_all_plugins: true

# Additional plugins you might want to enable:
# - global_position  # GPS position
# - local_position   # Local position
# - altitude         # Altitude data
# - battery          # Battery status
# - rc_io            # RC input/output
# - waypoint         # Mission waypoints
# - param            # Parameter management
# - ftp              # File transfer
# - command          # Command interface